### ISSUE TITLE
Windows MSVC++ 64-bit binary

### ISSUE THREAD

**Issue by a1880** [muhos/SeqFROST#1]
Thank you for this masterpiece solver!

I ported it to Microsoft Visual C++ 2022.
The console output color handling required a bit of tweaking.

Greetings!

Axel Kemper

[akSeqFROST.zip](https://github.com/muhos/SeqFROST/files/9456213/akSeqFROST.zip)

**Comment by muhos** [comment]
Thanks! it was a headache for me too to display.

**Comment by a1880** [comment]
I include the changed files here
[colors.zip](https://github.com/muhos/SeqFROST/files/9628366/colors.zip)

Add the following:

```
int main(int argc, char **argv)
{             
	//  enable processing of ANSI control sequences for console colors
	color_console_init();
```
